version: 1
reporting: checks-v1
policy:
  pullRequests: public
tasks:
  $match:
    'true':
      taskId:
        $eval: as_slugid("?")
      provisionerId: built-in
      workerType: succeed
      deadline: '${fromNow("1 day")}'
      expires: '${fromNow("1 day")}'
      payload: {}
      extra:
          event: {$eval: 'event'}
      metadata:
        name: 'did-run'
        description: 'check'
        owner: '${event.sender.login}@users.noreply.github.com'
        source: '${event.repository.url}'
