---
trust-domain: releng

task-priority: lowest
taskgraph:
    repositories:
        releng:
            name: Redo
    register: redo_taskgraph:register

workers:
    aliases:
        images:
            provisioner: releng-{level}
            implementation: docker-worker
            os: linux
            worker-type: linux
        t-linux:
            provisioner: releng-t
            implementation: docker-worker
            os: linux
            worker-type: linux
        pypi:
            provisioner: scriptworker-k8s
            worker-type: releng-1-pypi-dev
            os: scriptworker
            implementation: scriptworker-pypi

scriptworker:
    scope-prefix: project:releng
